name: Run Python Script

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Updated to v3 to avoid deprecated Node.js version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4 to avoid deprecated Node.js version
      with:
        python-version: '3.x'  # Replace with the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python generate_chart_notes.py

